<?php
$z[0]=Array("global","",1016,1048);
$z[0][4]=array();
$z[0][4]['name']="cfg_templets_skin";
$z[1]=Array("global","",1119,1151);
$z[1][4]=array();
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("channel","\r\n				<a  id=\"nav_2\" href=\"[field:typelink/]\">[field:typename/]</a> \r\n				",1528,1742);
$z[2][4]=array();
$z[2][4]['row']="5";
$z[2][4]['type']="top";
$z[2][4]['currentstyle']="<a href='~typelink~' class='thisclass current'>~typename~</a>";
$z[3]=Array("global","",2418,2445);
$z[3][4]=array();
$z[3][4]['name']="cfg_indexurl";
$z[4]=Array("global","",2711,2738);
$z[4][4]=array();
$z[4][4]['name']="cfg_indexurl";
$z[5]=Array("global","",3247,3279);
$z[5][4]=array();
$z[5][4]['name']="cfg_templets_skin";
$z[6]=Array("global","",8265,8297);
$z[6][4]=array();
$z[6][4]['name']="cfg_templets_skin";
$z[7]=Array("global","",9737,9769);
$z[7][4]=array();
$z[7][4]['name']="cfg_templets_skin";

?>